### ISSUE TITLE
一个错误，请协助

### ISSUE THREAD

**Issue by norlover** [rssnsj/minivtun#1]
1.服务端配置 
/usr/sbin/minivtun -l 0.0.0.0:1717 -a 172.16.0.1/172.16.0.11 -n minivtun-go0 -e WaWaWaWa -d
iptables -t nat -A POSTROUTING ! -o lo -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_forward

客户端配置成功后

解析正常，无DNS劫持，tracert 正常，可以通过172.16.0.1

ping正常，但是就是打不开网页，非常奇怪，可能是mtu造成的，请大牛帮忙看看。

另外您的这个VPN是可以传输UDP的吧？

C:\Users\John>tracert -d 173.194.72.100

通过最多 30 个跃点跟踪到 173.194.72.100 的路由

  1    <1 毫秒    2 ms    <1 毫秒 192.168.1.1
  2   242 ms   241 ms   229 ms  172.16.0.1
  3   245 ms   239 ms   235 ms  128.199.127.254
  4   240 ms   230 ms   219 ms  103.253.144.233
  5   237 ms   240 ms   241 ms  202.79.197.30
  6   246 ms   250 ms   263 ms  209.85.243.156
  7   309 ms   309 ms   300 ms  216.239.40.230
  8   292 ms   285 ms   283 ms  209.85.241.149
  9   298 ms   297 ms   286 ms  209.85.243.21
 10     *        *        *     请求超时。
 11   279 ms   285 ms   291 ms  173.194.72.100

跟踪完成。

C:\Users\John>ping google.com

正在 Ping google.com [173.194.72.100] 具有 32 字节的数据:
来自 173.194.72.100 的回复: 字节=32 时间=296ms TTL=49

173.194.72.100 的 Ping 统计信息:
    数据包: 已发送 = 1，已接收 = 1，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 296ms，最长 = 296ms，平均 = 296ms
Control-C
^C
C:\Users\John>

**Comment by boytm** [comment]
tracert 证明 minivtun 是正常发挥作用的。打不开网页，是其它问题导致的，你仔细排查排查
