### ISSUE TITLE
如何通过minivtun访问google, facebook等

### ISSUE THREAD

**Issue by gavinshao** [rssnsj/minivtun#22]
sever (aws vps ): /usr/sbin/minivtun -l 0.0.0.0:555 -a 10.7.0.1/24  -e password -n mv0 -v 172.31.0.1/20=10.7.0.23 
server 内网ip172.31.12.87 
client :（Gateway 192.168.0.1）:/usr/sbin/minivtun -r vpn.aigg.shop:555 -a 10.7.0.23/24 -e password -n mv0 -d
client :ip route replace  52.53.223.4/32 dev eth0 via 192.168.0.1
           ip route change default dev mv0 via 10.7.0.164 bytes from 172.31.12.87: icmp_seq=697 ttl=255 time=184 ms

64 bytes from 10.7.0.1: icmp_seq=1 ttl=255 time=167 ms
64 bytes from 10.7.0.1: icmp_seq=2 ttl=255 time=167 ms
64 bytes from 10.7.0.1: icmp_seq=3 ttl=255 time=167 ms
64 bytes from 10.7.0.1: icmp_seq=4 ttl=255 time=167 ms
64 bytes from 10.7.0.1: icmp_seq=5 ttl=255 time=168 ms
64 bytes from 10.7.0.1: icmp_seq=6 ttl=255 time=168 ms
64 bytes from 10.7.0.1: icmp_seq=7 ttl=255 time=167 ms

64 bytes from 172.31.12.87: icmp_seq=698 ttl=255 time=184 ms
64 bytes from 172.31.12.87: icmp_seq=699 ttl=255 time=184 ms
64 bytes from 172.31.12.87: icmp_seq=700 ttl=255 time=184 ms
64 bytes from 172.31.12.87: icmp_seq=701 ttl=255 time=184 ms
64 bytes from 172.31.12.87: icmp_seq=702 ttl=255 time=184 ms

以上独能ping通，但ping www.google.com 不可以，要怎么配置

**Comment by boytm** [comment]
本地 Linux minivtun 启动后，还需要添加路由：
1. 获取一份 US 或者 非大陆 的路由表，可以直接参考 chnroute 项目 https://raw.githubusercontent.com/sabersalv/freedom-routes/dist/linux.tar.gz

2. 类似下面逐个添加路由。
```
ip route add xxxx/net via 10.7.0.1 dev  mv0 
```
其实上面项目有现成 routes-up.sh 直接执行应该就好。不行就稍微修改下里面 gateway 语法

**Comment by gavinshao** [comment]
sever :  /usr/sbin/minivtun -l 0.0.0.0:1194 -a 10.7.0.1/24  -e password -n mv0 
client: /usr/sbin/minivtun -r {server_vps_ip}:1194 -a 10.7.0.23/24 -e password -n tun0 -d
   linux  下执行以下:
      /sbin/ip route add {server_vps_ip}/32 via 192.168.0.1
      /sbin/ip route add 0.0.0.0/1 via 10.7.0.23
     /sbin/ip route add 128.0.0.0/1 via 10.7.0.23
     /sbin/ip route add 10.7.0.1/32 via 10.7.0.23
mac 下执行以下：
    sudo route add -net {server_vps_ip}/32 via 192.168.0.1
    sudo route add -net 0.0.0.0/1 via 10.7.0.23
    sudo route add -net 128.0.0.0/1 via 10.7.0.23
    sudo route add -net 10.7.0.1/32 via 10.7.0.23
