### ISSUE TITLE
client ping client timeout

### ISSUE THREAD

**Issue by E2vi** [rssnsj/minivtun#8]
A Server 、B Client、C Client

A<<--------->>B  ok
A<<--------->>C  ok
B<<--------->>C  timeout

B和C之间不能通过A来中转？以后有没有支持的计划？

**Comment by rssnsj** [comment]
> A Server 、B Client、C Client
> 
> A<<--------->>B ok
> A<<--------->>C ok
> B<<--------->>C timeout
> 
> B和C之间不能通过A来中转？以后有没有支持的计划？

直接打开Linux的 ip_forward 即可。

**Comment by 777s** [comment]
之前的测试可能有问题，现在重新测试是通的，但是在B ping C的时候提示“From 10.33.0.1: icmp_seq=2 Redirect Host(New nexthop: 10.33.0.3)”，这个是正常的？

A Server 10.33.0.1 
B Client 10.33.0.2 
C Client 10.33.0.3

[root@DnsMasq ~]# ping 10.33.0.1
PING 10.33.0.1 (10.33.0.1) 56(84) bytes of data.
64 bytes from 10.33.0.1: icmp_seq=1 ttl=64 time=34.4 ms
64 bytes from 10.33.0.1: icmp_seq=2 ttl=64 time=32.8 ms
64 bytes from 10.33.0.1: icmp_seq=3 ttl=64 time=32.6 ms
64 bytes from 10.33.0.1: icmp_seq=4 ttl=64 time=34.0 ms
64 bytes from 10.33.0.1: icmp_seq=5 ttl=64 time=32.9 ms
64 bytes from 10.33.0.1: icmp_seq=6 ttl=64 time=34.2 ms
^C
--- 10.33.0.1 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5174ms
rtt min/avg/max/mdev = 32.630/33.535/34.403/0.728 ms

[root@DnsMasq ~]# ping 10.33.0.3
PING 10.33.0.3 (10.33.0.3) 56(84) bytes of data.
64 bytes from 10.33.0.3: icmp_seq=1 ttl=63 time=93.6 ms
From 10.33.0.1: icmp_seq=2 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=2 ttl=63 time=95.0 ms
From 10.33.0.1: icmp_seq=3 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=3 ttl=63 time=99.7 ms
From 10.33.0.1: icmp_seq=4 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=4 ttl=63 time=94.0 ms
From 10.33.0.1: icmp_seq=5 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=5 ttl=63 time=94.5 ms
^C
--- 10.33.0.3 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4518ms
rtt min/avg/max/mdev = 93.688/95.421/99.795/2.266 ms

**Comment by boytm** [comment]
当 ABC 处于同一网段时候， A 会告诉 BC，你俩直接通过链路层就可以通信，你们之间的通信不必先把包交给我。所以提示
“From 10.33.0.1: icmp_seq=2 Redirect Host(New nexthop: 10.33.0.3)”

我猜测你B上路由规则是
ip route add default via A dev mv0
你只需在 B 上加一条 路由规则就行了
ip route add ABC_subnet/prefix via dev mv0

**Comment by 777s** [comment]
@boytm 说的有道理，但是B上面default route指向的是上层路由器并非A的地址，并且还有一个现象并不是每一个ping包都会有提示，按你的说法“ A 会告诉 BC，你俩直接通过链路层就可以通信”，这个在非VPN，非隧道环境，我认为是完全正常没有问题的，二层之间互相学习ARP，MAC通讯即可，但是在VPN环境，隧道环境下，同网段之间的互访不会学习ARP，理论上就应该扔到隧道给10.33.0.1处理，自然也应该没有这样的提示才对。

[root@DnsMasq ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
8.8.4.4         10.88.16.112    255.255.255.255 UGH   0      0        0 eth0
8.8.8.8         10.88.16.112    255.255.255.255 UGH   0      0        0 eth0
10.88.16.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.33.0.0       0.0.0.0         255.255.255.0   U     0      0        0 mv0
10.99.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth1
10.152.10.0     10.88.16.112    255.255.255.0   UG    0      0        0 eth0
10.7.0.0        10.88.16.112    255.255.255.0   UG    0      0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1003   0        0 eth1
0.0.0.0         10.88.16.1      0.0.0.0         UG    0      0        0 eth0

[root@DnsMasq ~]# ip route list
8.8.4.4 via 10.88.16.112 dev eth0 
8.8.8.8 via 10.88.16.112 dev eth0 
10.88.16.0/24 dev eth0  proto kernel  scope link  src 10.88.16.12 
10.33.0.0/24 dev mv0  proto kernel  scope link  src 10.33.0.2 
10.99.0.0/24 dev eth1  proto kernel  scope link  src 10.99.0.1 
10.152.10.0/24 via 10.88.16.112 dev eth0 
10.7.0.0/24 via 10.88.16.112 dev eth0 
169.254.0.0/16 dev eth0  scope link  metric 1002 
169.254.0.0/16 dev eth1  scope link  metric 1003 
default via 10.88.16.1 dev eth0 

[root@DnsMasq ~]# ping 10.33.0.3
PING 10.33.0.3 (10.33.0.3) 56(84) bytes of data.
64 bytes from 10.33.0.3: icmp_seq=1 ttl=63 time=105 ms
From 10.33.0.1: icmp_seq=2 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=2 ttl=63 time=100 ms
From 10.33.0.1: icmp_seq=3 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=3 ttl=63 time=100 ms
From 10.33.0.1: icmp_seq=4 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=4 ttl=63 time=94.2 ms
From 10.33.0.1: icmp_seq=5 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=5 ttl=63 time=94.2 ms
From 10.33.0.1: icmp_seq=6 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=6 ttl=63 time=94.8 ms
64 bytes from 10.33.0.3: icmp_seq=7 ttl=63 time=96.4 ms
From 10.33.0.1: icmp_seq=8 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=8 ttl=63 time=95.5 ms
64 bytes from 10.33.0.3: icmp_seq=9 ttl=63 time=95.0 ms
64 bytes from 10.33.0.3: icmp_seq=10 ttl=63 time=95.5 ms
From 10.33.0.1: icmp_seq=11 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=11 ttl=63 time=95.7 ms
64 bytes from 10.33.0.3: icmp_seq=12 ttl=63 time=99.0 ms
64 bytes from 10.33.0.3: icmp_seq=13 ttl=63 time=94.7 ms
64 bytes from 10.33.0.3: icmp_seq=14 ttl=63 time=94.2 ms
64 bytes from 10.33.0.3: icmp_seq=15 ttl=63 time=99.2 ms
64 bytes from 10.33.0.3: icmp_seq=16 ttl=63 time=96.3 ms
From 10.33.0.1: icmp_seq=17 Redirect Host(New nexthop: 10.33.0.3)
64 bytes from 10.33.0.3: icmp_seq=17 ttl=63 time=94.3 ms
64 bytes from 10.33.0.3: icmp_seq=18 ttl=63 time=94.7 ms
64 bytes from 10.33.0.3: icmp_seq=19 ttl=63 time=95.5 ms
64 bytes from 10.33.0.3: icmp_seq=20 ttl=63 time=96.5 ms
64 bytes from 10.33.0.3: icmp_seq=21 ttl=63 time=93.6 ms
64 bytes from 10.33.0.3: icmp_seq=22 ttl=63 time=94.0 ms
64 bytes from 10.33.0.3: icmp_seq=23 ttl=63 time=94.8 ms
64 bytes from 10.33.0.3: icmp_seq=24 ttl=63 time=94.1 ms
64 bytes from 10.33.0.3: icmp_seq=25 ttl=63 time=99.3 ms
64 bytes from 10.33.0.3: icmp_seq=26 ttl=63 time=95.3 ms
64 bytes from 10.33.0.3: icmp_seq=27 ttl=63 time=95.9 ms
64 bytes from 10.33.0.3: icmp_seq=28 ttl=63 time=96.9 ms
64 bytes from 10.33.0.3: icmp_seq=29 ttl=63 time=95.6 ms
